### ISSUE TITLE
Script crashes in IE 11

### ISSUE THREAD

**Issue by ffork** [treaty-io/treaty.io#1]
When loading the script in IE 11, the script crashes with the following error:

SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: treaty.js, Line: 1, Column: 134476

**Comment by etienne-martin** [comment]
Thanks, we'll look into that.

**Comment by etienne-martin** [comment]
Fixed, it's now working in IE 9, 10 & 11.

Let us know if you have another issue.

Thanks again.
